### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Exef** [tpetricek/TheGamma#5]
@tpetricek: Tomas - can you add any license to this project? I don't know if I can work with your code. 

Btw. Thanks for the great presentation on DevDay.

**Comment by tpetricek** [comment]
Sorry for the delay. I'll add Apache 2 license, but since @Krzysztof-Cieslak already contributed, I think I should get his agreement first.

**Comment by Krzysztof-Cieslak** [comment]
Whatever You want. Apache 2 is OK.
